//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetRepositoryServices.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssetTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssetTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AssetRepositoryServices.Resources.AssetTexts", typeof(AssetTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Backend_AssetServices_UserSchema_AssetServices_DisplayName {
            get {
                return ResourceManager.GetString("Backend_AssetServices_UserSchema_AssetServices_DisplayName", resourceCulture);
            }
        }
        
        public static string Backend_AssetServices_UserSchema_Swagger_DisplayName {
            get {
                return ResourceManager.GetString("Backend_AssetServices_UserSchema_Swagger_DisplayName", resourceCulture);
            }
        }
        
        public static string Backend_AssetServices_Api_SystemFullAccess {
            get {
                return ResourceManager.GetString("Backend_AssetServices_Api_SystemFullAccess", resourceCulture);
            }
        }
        
        public static string Backend_AssetServices_Api_SystemReadOnlyAccess {
            get {
                return ResourceManager.GetString("Backend_AssetServices_Api_SystemReadOnlyAccess", resourceCulture);
            }
        }
        
        public static string Backend_AssetServices_Api_TenantFullAccess {
            get {
                return ResourceManager.GetString("Backend_AssetServices_Api_TenantFullAccess", resourceCulture);
            }
        }
        
        public static string Backend_AssetServices_Api_TenantReadOnlyAccess {
            get {
                return ResourceManager.GetString("Backend_AssetServices_Api_TenantReadOnlyAccess", resourceCulture);
            }
        }
        
        public static string Graphql_Type_IsFinal_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_IsFinal_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Type_Description_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_Description_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Type_IsAbstract_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_IsAbstract_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Type_CkTypeId_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_CkTypeId_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Type_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Type_Filter_Attributes_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_Filter_Attributes_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Type_DerivedTypes_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_DerivedTypes_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Type_BaseType_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_BaseType_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Record_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Record_Description_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_Description_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Record_IsAbstract_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_IsAbstract_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Record_IsFinal_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_IsFinal_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Record_CkRecordId_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_CkRecordId_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Record_DerivedRecords_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_DerivedRecords_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Record_Filter_Attributes_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_Filter_Attributes_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Record_BaseRecord_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_BaseRecord_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Enum_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Enum_Description_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_Description_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Enum_UseFlags_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_UseFlags_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Enum_Values_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_Values_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Enum_CkEnumId_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_CkEnumId_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Model_Description_Description {
            get {
                return ResourceManager.GetString("Graphql_Model_Description_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Enum_IsExtensible_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_IsExtensible_Description", resourceCulture);
            }
        }
        
        public static string Graphql_EnumValue_Description {
            get {
                return ResourceManager.GetString("Graphql_EnumValue_Description", resourceCulture);
            }
        }
        
        public static string Graphql_EnumValue_Key_Description {
            get {
                return ResourceManager.GetString("Graphql_EnumValue_Key_Description", resourceCulture);
            }
        }
        
        public static string Graphql_EnumValue_Description_Description {
            get {
                return ResourceManager.GetString("Graphql_EnumValue_Description_Description", resourceCulture);
            }
        }
        
        public static string Graphql_EnumValue_Name_Description {
            get {
                return ResourceManager.GetString("Graphql_EnumValue_Name_Description", resourceCulture);
            }
        }
        
        public static string Graphql_EnumValue_IsExtension_Description {
            get {
                return ResourceManager.GetString("Graphql_EnumValue_IsExtension_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Enum_CkExtensionUpdateOperations_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_CkExtensionUpdateOperations_Description", resourceCulture);
            }
        }
        
        public static string Graphql_CkMutation_CkId_Description {
            get {
                return ResourceManager.GetString("Graphql_CkMutation_CkId_Description", resourceCulture);
            }
        }
        
        public static string Graphql_CkMutation_CkIds_Description {
            get {
                return ResourceManager.GetString("Graphql_CkMutation_CkIds_Description", resourceCulture);
            }
        }
        
        public static string Graphql_CkMutation_Description {
            get {
                return ResourceManager.GetString("Graphql_CkMutation_Description", resourceCulture);
            }
        }
        
        public static string Graphql_RtQueryRow_Description {
            get {
                return ResourceManager.GetString("Graphql_RtQueryRow_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Arguments_AttributePathsFilter_Description {
            get {
                return ResourceManager.GetString("Graphql_Arguments_AttributePathsFilter_Description", resourceCulture);
            }
        }
        
        public static string Graphql_RtQueryCell_Description {
            get {
                return ResourceManager.GetString("Graphql_RtQueryCell_Description", resourceCulture);
            }
        }
        
        public static string Graphql_RtQueryCell_AttribuePath_Description {
            get {
                return ResourceManager.GetString("Graphql_RtQueryCell_AttribuePath_Description", resourceCulture);
            }
        }
        
        public static string Graphql_RtQueryCell_Value_Description {
            get {
                return ResourceManager.GetString("Graphql_RtQueryCell_Value_Description", resourceCulture);
            }
        }
        
        public static string Graphql_RtQueryCellInput_Description {
            get {
                return ResourceManager.GetString("Graphql_RtQueryCellInput_Description", resourceCulture);
            }
        }
        
        public static string Graphql_RtQueryRowUpdate_Item_Description {
            get {
                return ResourceManager.GetString("Graphql_RtQueryRowUpdate_Item_Description", resourceCulture);
            }
        }
        
        public static string Graphql_RtQuery_Description {
            get {
                return ResourceManager.GetString("Graphql_RtQuery_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Type_Filter_AttributeNameContainsFilter_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_Filter_AttributeNameContainsFilter_Description", resourceCulture);
            }
        }
        
        public static string Graphql_RtQueryColumn_Description {
            get {
                return ResourceManager.GetString("Graphql_RtQueryColumn_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Type_Filter_IgnoreAbstractTypes_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_Filter_IgnoreAbstractTypes_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Type_DirectAndIndirectDerivedTypes_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_DirectAndIndirectDerivedTypes_Description", resourceCulture);
            }
        }
        
        public static string Graphql_Type_Filter_IncludeSelfArgs_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_Filter_IncludeSelfArgs_Description", resourceCulture);
            }
        }
        
        public static string Api_Title {
            get {
                return ResourceManager.GetString("Api_Title", resourceCulture);
            }
        }
        
        public static string Api_Description {
            get {
                return ResourceManager.GetString("Api_Description", resourceCulture);
            }
        }
    }
}
