//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetRepositoryServices.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssetTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssetTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssetRepositoryServices.Resources.AssetTexts", typeof(AssetTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full access to system API.
        /// </summary>
        public static string Backend_AssetServices_Api_FullAccess {
            get {
                return ResourceManager.GetString("Backend_AssetServices_Api_FullAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly access to system API.
        /// </summary>
        public static string Backend_AssetServices_Api_ReadOnlyAccess {
            get {
                return ResourceManager.GetString("Backend_AssetServices_Api_ReadOnlyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octo Mesh Admin Panel.
        /// </summary>
        public static string Backend_AssetServices_UserSchema_AdminPanel_DisplayName {
            get {
                return ResourceManager.GetString("Backend_AssetServices_UserSchema_AdminPanel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Repository Services UI.
        /// </summary>
        public static string Backend_AssetServices_UserSchema_AssetServices_DisplayName {
            get {
                return ResourceManager.GetString("Backend_AssetServices_UserSchema_AssetServices_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Repository Service Swagger UI.
        /// </summary>
        public static string Backend_AssetServices_UserSchema_Swagger_DisplayName {
            get {
                return ResourceManager.GetString("Backend_AssetServices_UserSchema_Swagger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction kit enum id, the unique identifier of the enum..
        /// </summary>
        public static string Graphql_Enum_CkEnumId_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_CkEnumId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition of a construction kit record with name and attributes..
        /// </summary>
        public static string Graphql_Enum_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional description of the record..
        /// </summary>
        public static string Graphql_Enum_Description_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the enum is a flags enum.
        /// </summary>
        public static string Graphql_Enum_UseFlags_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_UseFlags_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values of the enum..
        /// </summary>
        public static string Graphql_Enum_Values_Description {
            get {
                return ResourceManager.GetString("Graphql_Enum_Values_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional description of the model..
        /// </summary>
        public static string Graphql_Model_Description_Description {
            get {
                return ResourceManager.GetString("Graphql_Model_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base record the current record is derived from..
        /// </summary>
        public static string Graphql_Record_BaseRecord_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_BaseRecord_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction kit record id, the unique identifier of the record..
        /// </summary>
        public static string Graphql_Record_CkRecordId_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_CkRecordId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists types that are derived from the current construction kit record..
        /// </summary>
        public static string Graphql_Record_DerivedRecords_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_DerivedRecords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition of a construction kit record with name and attributes..
        /// </summary>
        public static string Graphql_Record_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional description of the record..
        /// </summary>
        public static string Graphql_Record_Description_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to filter for specific attribute names within construction kit records..
        /// </summary>
        public static string Graphql_Record_Filter_Attributes_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_Filter_Attributes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if the record is abstract..
        /// </summary>
        public static string Graphql_Record_IsAbstract_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_IsAbstract_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if the record is final..
        /// </summary>
        public static string Graphql_Record_IsFinal_Description {
            get {
                return ResourceManager.GetString("Graphql_Record_IsFinal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base type the current type is derived from..
        /// </summary>
        public static string Graphql_Type_BaseType_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_BaseType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction kit type id, the unique identifier of the type..
        /// </summary>
        public static string Graphql_Type_CkTypeId_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_CkTypeId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists types that are derived from the current construction kit type..
        /// </summary>
        public static string Graphql_Type_DerivedTypes_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_DerivedTypes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition of a construction kit type with name, associations and attributes..
        /// </summary>
        public static string Graphql_Type_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional description of the type..
        /// </summary>
        public static string Graphql_Type_Description_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to filter for specific attribute names within construction kit types..
        /// </summary>
        public static string Graphql_Type_Filter_Attributes_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_Filter_Attributes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if the type is abstract..
        /// </summary>
        public static string Graphql_Type_IsAbstract_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_IsAbstract_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if the type is final..
        /// </summary>
        public static string Graphql_Type_IsFinal_Description {
            get {
                return ResourceManager.GetString("Graphql_Type_IsFinal_Description", resourceCulture);
            }
        }
    }
}
